### ISSUE TITLE
Compile error using mqtt_auth example - 'sent' was not declared MQTT.cpp

### ISSUE THREAD

**Issue by myk3y** [Imroy/pubsubclient#17]
>/Development/Arduino/libraries/pubsubclient/src/MQTT.cpp: In member function 'bool MQTT::Message::send(Client&)':
>//Development/Arduino/libraries/pubsubclient/src/MQTT.cpp:123:5: error: 'sent' was not >declared in this scope
>     sent = client.write(const_cast<const uint8_t*>(packet), packet_length);
>     ^
>Error compiling.

**Comment by av1024** [comment]
Just add `uint32_t ` before `sent`

**Comment by myk3y** [comment]
Thanks Alex!
