### ISSUE TITLE
can't connect with String hostname

### ISSUE THREAD

**Issue by marciogranzotto** [Imroy/pubsubclient#27]
I've set up a DDNS on my router and I'm tring to connect the ESP with your library using the constructor client(wclient, server) where server is a String with my hostname, Ex. "mybroker.ddns.net".

However this does not work.

**Comment by Imroy** [comment]
Hmm, I'm seeing this too. I'll see what I can find.

**Comment by Sushinn** [comment]
@Imroy maybe I could use the mDNS address of my broker (a raspberry pi), raspberrypi2.local, whould this work?

I'll try as soon as possible

**Comment by Sushinn** [comment]
Solved the problem declaring the hostname as a char array, not a string. (Ex.: char server[] = "mybroker,ddns.net")

However, I can't do the same with the mDNS/Bonjur address of my broker. Maybe a mDNS resolver is necessary?
