### ISSUE TITLE
unsubscribe bug fix

### ISSUE THREAD

**Issue by mtnbrit** [Imroy/pubsubclient#38]
Hi in the src/MQTT.cpp file you are distributing with your pubsubclient, there are two errors around line 646
 ```
// Unsubscribe class
  Unsubscribe::Unsubscribe() :
    Message(SUBSCRIBE),
    _buffer(NULL), _buflen(0)
  {
    _need_packet_id = true;
  }

  Unsubscribe::Unsubscribe(String topic) :
    Message(SUBSCRIBE),
    _buffer(NULL), _buflen(0)
  {
```

the two instances of Message(SUBSCRIBE) should clearly be Message(UNSUBSCRIBE)

Ive run into this and fixing it makes unsubbing work,thx.

**Comment by Imroy** [comment]
Thanks for spotting that!
