### ISSUE TITLE
QOS 1 Puback

### ISSUE THREAD

**Issue by MikeSchafer** [Imroy/pubsubclient#43]
When the client receives a qos = 1 publish from the server, it does not include the packet ID of the received packet in the puback.

**Comment by MikeSchafer** [comment]
Correction -- There is no response code in a puback, just the packet ID of the received packet.

**Comment by Imroy** [comment]
Sorry for not dealing with this sooner. THKDev just fixed this :P

**Comment by MikeSchafer** [comment]
Thanks.

Mike

----------------------------------------------------------------------------------------------------------
R. Michael Schafer, Ph.D.                     E-mail: RMSchafer@nd.edu
Teaching Professor                              Phone: (574) 631-4851
273 Fitzpatrick HL ENGRNG
Department of Electrical Engineering
University of Notre Dame
Notre Dame, IN 46556
