### ISSUE TITLE
does this Pubsubclient now support LWT?

### ISSUE THREAD

**Issue by dogrocker** [Imroy/pubsubclient#5]
I didn't found Last Will Testament yet in the Pubsubclient API function.

So do you will add this function soon ?

Thanks.

**Comment by Imroy** [comment]
Use the set_will() method on a Connect object.
````
  client.connect(MQTT::Connect("ESP8266").set_will("status", "down"));
````
Should I put this in an example, or document the use of these objects and methods more? Or both?

**Comment by dogrocker** [comment]
Thanks @Imroy for fast response. Sorry for my mistake I just scan with `lwt, last will` key word.

I think it will be good for beginner if you can docs all api in `readme.md`.
