### ISSUE TITLE
mqtt_basic example throws: "'MQTT' does not name a type" error.

### ISSUE THREAD

**Issue by alexhalford** [Imroy/pubsubclient#52]
Using the Arduino IDE, and latest version of the PubSubClient library. Hardware is Sparkfun 'Thing' ESP8266 board. Error thrown at:

    void callback(const MQTT::Publish& pub)

I've tried reinstalling the whole IDE from scratch, etc. 

Thanks in advance :)

**Comment by HW-Siew** [comment]
Hi @alexhalford, have you downloaded the correct PubSubClient library. There are two with the same name.

**Comment by Testato** [comment]
And you must not update by library manager ;-)

**Comment by alexhalford** [comment]
Hi, yes, that solved the problem. I didn't know there were two :/

Thanks :)
