### ISSUE TITLE
OTA over MQTT

### ISSUE THREAD

**Issue by ionciubotaru** [Imroy/pubsubclient#64]
I tried OTA using test.mosquitto.org
The update works fine except:

```
    Serial.println("Clearing retained message.");
    client.publish(MQTT::Publish(pub.topic(), "")
                   .set_retain());
```

Client doesn't publish anything, so ESP update again and again
I tried:

```
    Serial.println("Clearing retained message.");
    client.publish(MQTT::Publish(pub.topic(), "")
                   .set_retain(true));
```

but it doesn't work - nothing is published on mqtt server.

**Comment by THKDev** [comment]
Remove pub.payload_stream()->stop();
Do NOT stop the client connection because the (WiFi) Client hold in class Publish is NOT ref counted. It is only a pointer. Closing it will count ref to 0 and close the TCP connection.
