### ISSUE TITLE
Can't pass 'this' to callback scope

### ISSUE THREAD

**Issue by jmas** [Imroy/pubsubclient#9]
Hello. I'm not super-c++ programmer, but I found that I can't pass `'this'` to lambda-function when I work with `set_callback()`. I want to do something like this:
```cpp
        mqttClient.set_callback([this](const MQTT::Publish& pub){
            for (int i=0; i<eventsSize; ++i) {
                if (pub.topic() == events[i].name) {
                    events[i].callback(pub.payload_string());
                }
            }
        });
```
`eventsSize`, `events` is members of top-class scope where this code is present. In current  `PubSubClien.h` I do not found way to work with `eventsSize`, `events` inside lambda-function.

So I did some modifications for `PubSubClien.h`:
```cpp
public:
//typedef void(*callback_t)(const MQTT::Publish&);

//...

std::function<void(const MQTT::Publish&)> _callback;
//callback_t _callback;

//..

PubSubClient& set_callback(std::function<void(const MQTT::Publish&)> cb) { _callback = cb; return *this; }
```
And now I can pass variables of different scope to lambda-function.

I can do Pull-Request with this modifications. But if you know right way to pass variables of different scope to lambda-function - please tell how I can do this.

**Comment by Imroy** [comment]
It's simpler to just redefine callback_t using std::function.

**Comment by jmas** [comment]
@Imroy, Can you show some code how to do this. I'm noob in this. :(

**Comment by Imroy** [comment]
Okay, good to hear you figured it out :)
